# MTKC POC EKS - ArgoCD App: Sample Applications
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 4: Application Deployment (ArgoCD)
# Sync Wave: 7 (after routes)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shanaka-versent/EKS-Istio-GatewayAPI-Deom.git
    targetRevision: HEAD
    path: k8s/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
